export const ADD_TODO = 'ADD TODO';
export const TOGGLE_TODO_COMPLETED = 'TOGGLE TODO_COMPLETED';
export const TOGGLE_TODO_INSPRINT = 'TOGGLE TODO_INSPRINT';
export const SET_VISIBILITY_FILTER = 'SET VISIBILITY FILTER';
export const SHOW_ALL = "SHOW_ALL";
export const SHOW_COMPLETED = "SHOW_COMPLETED";
export const SHOW_ACTIVE = "SHOW_ACTIVE";
export const SHOW_INSPRINT = "SHOW_INSPRINT";